FROM python:3.11-slim

WORKDIR /app

COPY . .

RUN pip install fastapi uvicorn langgraph langchain-groq langchain python-dotenv websockets psycopg2-binary

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]